name: umate
description: "University Life Improvement Utilites App"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mvc_pattern: ^8.12.0
  image_picker: any
  webview_flutter: any
  firebase_core: ^2.29.0
  firebase_auth: ^4.19.1
  cloud_firestore: ^4.16.1
  firebase_storage: ^11.7.1
  path: any
  auto_size_text: ^3.0.0
  intl: ^0.19.0
  sqflite: 2.0.0+3
  path_provider: 2.0.1
  flutter_staggered_grid_view: 0.4.0
  flutter_svg: ^0.22.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
