name: umate
description: "University Life Improvement Utilites App"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mvc_pattern: ^8.12.0
  pocketbase: ^0.18.1
  shared_preferences: any
  image_picker: any
  universal_html: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
