// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRzgF3JO7occGLkvlEqiBvJ3lWZlm3dVg',
    appId: '1:260237131689:web:e648b47af55a8a7ee10eb8',
    messagingSenderId: '260237131689',
    projectId: 'umate-astra',
    authDomain: 'umate-astra.firebaseapp.com',
    storageBucket: 'umate-astra.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzzoDUYLjwDyX0d6Eww7oSJzur5MuIFPs',
    appId: '1:260237131689:android:395963bef0101be1e10eb8',
    messagingSenderId: '260237131689',
    projectId: 'umate-astra',
    storageBucket: 'umate-astra.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRzgF3JO7occGLkvlEqiBvJ3lWZlm3dVg',
    appId: '1:260237131689:web:f3330d0e342e6510e10eb8',
    messagingSenderId: '260237131689',
    projectId: 'umate-astra',
    authDomain: 'umate-astra.firebaseapp.com',
    storageBucket: 'umate-astra.appspot.com',
  );
}
